### PR TITLE
[BUG] isHidden and isVisible assume that folks are using the same cla…

### PR DESCRIPTION
**Pull request by benkiefer**
…sses you are. Use :hidden and :visible instead

### CODE REVIEW

**Comment by toranb** [comment]
love it ! thanks @benkiefer

**Comment by toranb** [comment]
I just did an npm publish - the new version w/ your changes is 1.5.0

**Comment by benkiefer** [comment]
It looks like your tag didn't get pushed to github

**Comment by toranb** [comment]
ah, yes! Just pushed :)

**Pull request merged**
