### PR TITLE
[FEATURE] make the initializer to expose container part of the test-helpers addon

### PR DESCRIPTION
**Pull request by williamsbdev**
This will eliminate the need for every host app to setup this initializer.

### CODE REVIEW

**Comment by toranb** [comment]
I think the only issue (that you can confirm) is - will this ONLY be pulled into test code (not production builds) ?

**Comment by williamsbdev** [comment]
When I ran an `ember build --env=production` I did not see the test code initializer in the `dist/assets`. However, running the tests or the `ember build --env=test` did produce the initializer in the `dist/assets`.

**Comment by toranb** [comment]
Sounds good - should we do a full version bump on this to 0.6.0 then ?

**Comment by williamsbdev** [comment]
sounds good. This is a big change with the addition of the container
initializer.

**Comment by toranb** [comment]
Published as 0.6.0 on npm - let me know if you run into issues w/ this when you upgrade this week :)

**Pull request merged**
