### PR TITLE
[FEATURE] supporting fauxjax 1.X series API for QUnit.testDone callback

### PR DESCRIPTION
**Pull request by williamsbdev**

### CODE REVIEW

**Comment by toranb** [comment]
Wow dude this was a ton of work! Nice work on the upgrade! All tests are passing and the code looks good -anything I should know before we merge this?

**Comment by williamsbdev** [comment]
I don't think so. It should be good to go.

**Comment by toranb** [comment]
If you have time tonight - can you do the version bump + npm publish to ensure you get the version you wanted?

**Comment by williamsbdev** [comment]
I updated the README.md to note the versions of this library that are compatible with certain versions of [fauxjax](https://github.com/jarrodctaylor/fauxjax). I also pushed a tag 1.0.0 and published the corresponding version. Thanks for merging this PR!

**Pull request merged**
