### PR TITLE
allow the default wait for to be configurable by the application author

### PR DESCRIPTION
**Pull request by benkiefer**

### CODE REVIEW

**Comment by toranb** [comment]
Was this just an issue w/ travis-ci ? I pulled locally and it seems legit ...

**Comment by williamsbdev** [comment]
I believe it was.

**Comment by williamsbdev** [comment]
I say we merge this even though travis-ci is red. I am totally fine locally. I can open up an issue with travis-ci if you would like.

**Comment by benkiefer** [comment]
I removed the version bump so we can get this merged. Hopefully we can get a green build after that

**Comment by benkiefer** [comment]
That did it. Travis is sillly.

**Pull request merged**
