### PR TITLE
[FEATURE]: added waitFor helper to better support 3rd party libs

### PR DESCRIPTION
**Pull request by toranb**
Added the waitFor helper to support 3rd party lib in ember-testing (like foundation modal)

### CODE REVIEW

**Comment by williamsbdev** [comment]
This looks good to merge!

**Comment by toranb** [comment]
Excellent ! I'll do a version commit to 0.6.0 and publish it via npm

**Comment by toranb** [comment]
nevermind :) looks like you already did 0.5.2 

did you publish it yet ?

**Comment by williamsbdev** [comment]
I did the npm publish for 0.5.2. In hindsight, it should have probably been 0.6.0 as it added a new feature.

**Comment by toranb** [comment]
No worries - just glad to have this on npm now :)

**Pull request merged**
