### PR TITLE
Added user-friendly messages to 'input' assert statements 

### PR DESCRIPTION
**Pull request by ryanskow**

### CODE REVIEW

**Comment by toranb** [comment]
Looks like a solid improvement Ryan! I'll pull this in tonight and release a patch version so you'll have this tomorrow!

**Comment by toranb** [comment]
@williamsbdev did you also bump and publish this ?

**Comment by williamsbdev** [comment]
@toranb I did. You can now use the new features with version 2.0.1.

**Comment by ryanskow** [comment]
Thanks for the quick turn-around on this!

**Comment by toranb** [comment]
Agreed! Nice work @williamsbdev

**Pull request merged**
